config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
  }

  namespace :admins do
    root 'dashboards#index'
    resources :users, only: %i[index show destroy]
    resources :teams, only: %i[index show new edit create update destroy] do
      resources :team_invitations, only: %i[new create], module: :teams
    end
  end

  namespace :users do
    resource :team, only: %i[show] do
      resources :tasks, only: %i[show new edit create update destroy], module: :teams do
        member do
          patch :toggle
        end
      end
    end
  end

  resources :team_invitations, only: [] do
    collection do
      get :accept
    end
  end

  root 'static_pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :team

  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 255 }
  validates :completed, inclusion: { in: [true, false] }

  scope :default_order, -> { order(created_at: :desc, id: :desc) }
end

app/models/team.rb
class Team < ApplicationRecord
  has_one_attached :logo do |attachable|
    attachable.variant :thumb, resize_to_fill: [100, 100]
    attachable.variant :logo, resize_to_fill: [20, 20]
  end

  has_many :team_invitations, dependent: :destroy
  has_many :users, dependent: :nullify
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  scope :default_order, -> { order(:id) }
end

app/models/team_invitation.rb
class TeamInvitation < ApplicationRecord
  belongs_to :team

  before_validation :set_token, :set_expires_at, on: :create

  validates :email, presence: true
  validates :token, presence: true, uniqueness: true
  validates :expires_at, presence: true

  private

  def set_token
    self.token ||= SecureRandom.urlsafe_base64(32)
  end

  def set_expires_at
    self.expires_at ||= 1.day.from_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :team, optional: true

  validates :name, presence: true

  scope :default_order, -> { order(:id) }
end

app/controllers/admins/application_controller.rb
class Admins::ApplicationController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins/application'
end

app/controllers/admins/dashboards_controller.rb
class Admins::DashboardsController < Admins::ApplicationController
  def index
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    admins_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admins/teams/team_invitations_controller.rb
class Admins::Teams::TeamInvitationsController < Admins::ApplicationController
  before_action :set_team

  def new
    @invitation = @team.team_invitations.build
  end

  def create
    @invitation = @team.team_invitations.build(invitation_params)
    if @invitation.save
      TeamInvitationMailer.invite(@invitation).deliver_now
      redirect_to admins_team_path(@team), notice: 'チーム招待メールを送信しました。'
    else
      flash.now[:alert] = 'チーム招待メールを送信できませんでした。'
      render :new, status: :unprocessable_content
    end
  end

  private

  def invitation_params
    params.expect(team_invitation: %i[email])
  end

  def set_team
    @team = Team.find(params[:team_id])
  end
end

app/controllers/admins/teams_controller.rb
class Admins::TeamsController < Admins::ApplicationController
  before_action :set_team, only: %i[show edit update destroy]

  def index
    @teams = Team.default_order.page(params[:page])
  end

  def show
  end

  def new
    @team = Team.new
  end

  def edit
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to admins_team_path(@team), notice: 'チームを作成しました。'
    else
      flash.now[:alert] = 'チームを作成できませんでした。'
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @team.update(team_params)
      redirect_to admins_team_path(@team), notice: 'チーム情報を更新しました。'
    else
      flash.now[:alert] = 'チーム情報を更新できませんでした。'
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @team.destroy!
    redirect_to admins_teams_path, notice: 'チームを削除しました。', status: :see_other
  end

  private

  def team_params
    params.expect(team: %i[name logo])
  end

  def set_team
    @team = Team.find(params[:id])
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::ApplicationController
  before_action :set_user, only: %i[show destroy]

  def index
    @users = User.default_order.page(params[:page])
  end

  def show
  end

  def destroy
    @user.destroy!
    redirect_to admins_users_path, notice: 'ユーザーを削除しました。', status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  allow_browser versions: :modern

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/team_invitations_controller.rb
class TeamInvitationsController < ApplicationController
  def accept
    invitation = TeamInvitation.find_by(token: params[:token])

    if invitation.nil? || invitation.expires_at < Time.current
      redirect_to root_path, alert: '無効なリンクです。'
      return
    end

    if user_signed_in?
      ActiveRecord::Base.transaction do
        current_user.update!(team: invitation.team)
        invitation.destroy!
      end
      redirect_to root_path, notice: 'チームに参加しました。'
    else
      session[:team_invitation_token] = invitation.token
      redirect_to new_user_session_path, notice: 'ログインしてください。'
    end
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    if (token = session.delete(:team_invitation_token))
      invitation = TeamInvitation.find_by(token:)

      if invitation&.expires_at&.future?
        ActiveRecord::Base.transaction do
          resource.update!(team: invitation.team)
          invitation.destroy!
        end

        flash[:notice] = 'チームに参加しました。'
        root_path
      end
    end

    super
  end
end

app/controllers/users/teams/tasks_controller.rb
class Users::Teams::TasksController < Users::ApplicationController
  before_action :set_team
  before_action :set_task, only: %i[show edit update destroy toggle]

  def show
  end

  def new
    @task = @team.tasks.build
  end

  def edit
  end

  def create
    @task = @team.tasks.build(task_params)
    if @task.save
      redirect_to users_team_task_path(@task), notice: 'タスクを作成しました。'
    else
      flash.now[:alert] = 'タスクを作成できませんでした。'
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @task.update(task_params)
      redirect_to users_team_task_path(@task), notice: 'タスク情報を更新しました。'
    else
      flash.now[:alert] = 'タスク情報を更新できませんでした。'
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @task.destroy!
    redirect_to users_team_path, notice: 'タスクを削除しました。', status: :see_other
  end

  def toggle
    @task.update!(completed: !@task.completed)
    redirect_to users_team_path, notice: '完了状況を更新しました。'
  end

  private

  def task_params
    params.expect(task: %i[title description])
  end

  def set_team
    @team = current_user.team
  end

  def set_task
    @task = @team.tasks.find(params[:id])
  end
end

app/controllers/users/teams_controller.rb
class Users::TeamsController < Users::ApplicationController
  def show
    @team = current_user.team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/dashboards/index.html.haml
%h2.text-center 管理者ホーム

app/views/admins/teams/_form.html.haml
.row.justify-content-center
  .col-md-6
    = simple_form_for([:admins, team]) do |f|
      .form-inputs
        = f.input :name, autofocus: true
        = f.input :logo, as: :file

        - if team.logo.attached?
          .mt-2.text-center
            = image_tag team.logo.variant(:thumb),
                        class: 'img-fluid rounded'

      .form-actions.text-center.mb-3
        = f.button :submit, class: 'btn btn-outline-primary'

app/views/admins/teams/edit.html.haml
%h2.text-center.mb-3 チーム編集
= render 'admins/teams/form', team: @team

app/views/admins/teams/index.html.haml
%h2.text-center.mb-4 チーム一覧

.text-center.mb-4
  = link_to 'チームを追加', new_admins_team_path, class: 'btn btn-outline-secondary'

.row.justify-content-center
  .col-md-8
    - if @teams.exists?
      %table.table.table-bordered.align-middle.text-center
        %thead
          %tr
            %th.w-10 ID
            %th チーム名
            %th 操作
        %tbody
          - @teams.each do |team|
            %tr
              %td= team.id
              %td= team.name
              %td
                = link_to '詳細', admins_team_path(team), class: 'btn btn-sm btn-outline-secondary me-2'
                = link_to '編集', edit_admins_team_path(team), class: 'btn btn-sm btn-outline-warning me-2'
                = button_to '削除',
                            admins_team_path(team),
                            method: :delete,
                            data: { turbo_confirm: '本当に削除しますか？' },
                            form: { class: 'd-inline' },
                            class: 'btn btn-sm btn-outline-danger'
    - else
      %p.text-center チームがありません。

app/views/admins/teams/new.html.haml
%h2.text-center.mb-3 チーム作成
= render 'admins/teams/form', team: @team

app/views/admins/teams/show.html.haml
%h2.text-center.mb-4 チーム詳細

.row.justify-content-center
  .col-md-8
    %table.table.table-bordered.w-100
      %tbody
        %tr
          %th.text-center.w-25 チーム名
          %td= @team.name
        - if @team.logo.attached?
          %tr
            %th.text-center.w-25 チームロゴ
            %td= image_tag @team.logo.variant(:thumb), class: 'rounded-circle'
        - if @team.users.exists?
          %tr
            %th.text-center.w-25 チームメンバー一覧
            %td
              - @team.users.default_order.each do |user|
                = user.name

    .text-center
      .mb-3
        = link_to 'チームへ招待する', new_admins_team_team_invitation_path(@team), class: 'btn btn-link'
      .mb-3
        = link_to '一覧に戻る', admins_teams_path, class: 'btn btn-outline-secondary me-2'
        = link_to '編集する', edit_admins_team_path(@team), class: 'btn btn-outline-warning me-2'
        = button_to '削除する',
                    admins_team_path(@team),
                    method: :delete,
                    data: { turbo_confirm: '本当に削除しますか？' },
                    form: { class: 'd-inline' },
                    class: 'btn btn-outline-danger'

app/views/admins/teams/team_invitations/new.html.haml
%h2.text-center.mb-3 チーム招待

.row.justify-content-center
  .col-md-6
    = simple_form_for([:admins, @team, @invitation]) do |f|
      .form-inputs
        = f.input :email, autofocus: true

      .form-actions.text-center
        = f.button :submit, '招待する', class: 'btn btn-outline-primary'

app/views/admins/users/index.html.haml
%h2.text-center.mb-4 ユーザー一覧

.row.justify-content-center
  .col-md-8
    - if @users.exists?
      %table.table.table-bordered.align-middle.text-center
        %thead
          %tr
            %th.w-10 ID
            %th 名前
            %th メールアドレス
            %th 作成日
            %th 操作
        %tbody
          - @users.each do |user|
            %tr
              %td= user.id
              %td= user.name
              %td= user.email
              %td= l(user.created_at, format: :date)
              %td
                = link_to '詳細', admins_user_path(user), class: 'btn btn-sm btn-outline-secondary me-2'
                = button_to '削除',
                            admins_user_path(user),
                            method: :delete,
                            data: { turbo_confirm: '本当に削除しますか？' },
                            form: { class: 'd-inline' },
                            class: 'btn btn-sm btn-outline-danger'
    - else
      %p.text-center ユーザーがいません。

app/views/admins/users/show.html.haml
%h2.text-center.mb-4 ユーザー詳細

.row.justify-content-center
  .col-md-8
    %table.table.table-bordered.w-100
      %tbody
        %tr
          %th.text-center.w-25 ユーザー名
          %td= @user.name
        %tr
          %th.text-center.w-25 メールアドレス
          %td= @user.email
        %tr
          %th.text-center.w-25 作成日
          %td= l(@user.created_at, format: :date)
        %tr
          %th.text-center.w-25 所属チーム
          %td= @user.team.name

    .text-center
      .mb-3
        = link_to '一覧に戻る', admins_users_path, class: 'btn btn-outline-secondary me-2'
        = button_to '削除する',
                    admins_user_path(@user),
                    method: :delete,
                    data: { turbo_confirm: '本当に削除しますか？' },
                    form: { class: 'd-inline' },
                    class: 'btn btn-outline-danger'

app/views/layouts/admins/_sidebar.html.haml
.admin-sidebar.d-flex.flex-column.flex-shrink-0.p-3.bg-light
  = link_to admins_root_path, class: 'text-dark text-decoration-none' do
    %span.fs-4 Tasky管理画面
  %hr
  %ul.nav.nav-pills.flex-column.mb-auto
    %li.nav-item
      = link_to admins_root_path, class: 'nav-link text-black' do
        %i.bi.bi-house.icon-small.me-2
        管理者ホーム
    %li.nav-item
      = link_to admins_users_path, class: 'nav-link text-black' do
        %i.bi.bi-people.icon-small.me-2
        ユーザー一覧
    %li.nav-item
      = link_to admins_teams_path, class: 'nav-link text-black' do
        %i.bi.bi-microsoft-teams.icon-small.me-2
        チーム一覧

  %hr
  .dropdown
    %a.d-flex.align-items-center.link-body-emphasis.text-decoration-none.dropdown-toggle{ 'aria-expanded' => 'false', 'data-bs-toggle' => 'dropdown', :href => '#' }
      %i.bi.bi-person-fill.icon-middle.me-2
      %strong 管理者
    %ul.dropdown-menu.text-small.shadow
      %li
        = button_to 'ログアウト', destroy_admin_session_path, class: 'dropdown-item', method: :delete

app/views/layouts/admins/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    %title= content_for(:title) || 'Tasky'
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    %meta{ content: 'yes', name: 'apple-mobile-web-app-capable' }
    %meta{ content: 'yes', name: 'mobile-web-app-capable' }
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{ href: '/icon.png', rel: 'icon', type: 'image/png' }
    %link{ href: '/icon.svg', rel: 'icon', type: 'image/svg+xml' }
    %link{ href: '/icon.png', rel: 'apple-touch-icon' }
    = stylesheet_link_tag :app, 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  %body
    = render 'shared/toast'
    .d-flex.flex-nowrap
      = render 'layouts/admins/sidebar'
      .container.my-5
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    %title= content_for(:title) || 'Kazoku Quest'
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    %meta{ content: 'yes', name: 'apple-mobile-web-app-capable' }
    %meta{ content: 'yes', name: 'mobile-web-app-capable' }
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{ href: '/icon.png', rel: 'icon', type: 'image/png' }
    %link{ href: '/icon.svg', rel: 'icon', type: 'image/svg+xml' }
    %link{ href: '/icon.png', rel: 'apple-touch-icon' }
    = stylesheet_link_tag :app, 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  %body
    = render 'shared/toast'
    = render 'shared/header'
    .container.my-5
      = yield

app/views/shared/_header.html.haml
%header
  %nav.navbar.navbar-light.border-bottom.mb-4
    .container-fluid.d-flex.flex-column.align-items-center
      = link_to 'Tasky', root_path, class: 'navbar-brand fw-bold text-decoration-none fs-2'

      .d-flex.w-100.justify-content-between
        %ul.navbar-nav.d-flex.flex-row.gap-3
          %li.nav-item
            = link_to 'ホーム', root_path, class: 'nav-link ms-3'
          - if current_user&.team.present?
            %li.nav-item
              = link_to 'チーム', users_team_path, class: 'nav-link ms-3'

        %ul.navbar-nav.d-flex.flex-row.gap-3
          - if user_signed_in?
            %li.nav-item
              = link_to '#', class: 'btn btn-outline-success btn-sm d-flex align-items-center gap-2' do
                - if current_user.team&.logo&.attached?
                  = image_tag current_user.team.logo.variant(:logo),
                              class: 'rounded-circle'
                = current_user.name
            %li.nav-item
              = button_to 'ログアウト',
                          destroy_user_session_path,
                          method: :delete,
                          form: { class: 'd-inline' },
                          class: 'btn btn-outline-secondary btn-sm'
          - else
            %li.nav-item
              = link_to '新規登録', new_user_registration_path, class: 'btn btn-outline-success btn-sm'
            %li.nav-item
              = link_to 'ログイン', new_user_session_path, class: 'btn btn-outline-primary btn-sm me-3'

app/views/shared/_toast.html.haml
- if notice.present? || alert.present?
  .position-fixed.top-0.end-0.m-4.z-1
    .toast.show.align-items-center.border-0{
      class: class_names({ 'bg-primary': notice.present?, 'bg-danger': alert.present? }),
      role: 'alert'
    }
      .d-flex.align-items-center
        .toast-body.text-white.flex-grow-1
          = notice || alert
        %button.btn-close.btn-close-white.me-3.m-auto{ 'data-bs-dismiss': 'toast', type: 'button' }

app/views/static_pages/home.html.haml
%h1 StaticPages#home
%p Find me in app/views/static_pages/home.html.haml

app/views/users/teams/show.html.haml
.row.justify-content-center
  .col-md-6
    .text-center
      - if @team.logo.attached?
        = image_tag @team.logo.variant(:thumb), class: 'rounded-circle mb-3'

      %h2.fw-bold.mb-5= @team.name

      = link_to 'タスクを作成する', new_users_team_task_path, class: 'btn btn-outline-secondary btn-sm mb-3'

      %h4.mb-3 タスク一覧
      - if @team.tasks.exists?
        - @team.tasks.default_order.each do |task|
          .card.shadow-sm.mb-4{ class: task.completed? ? 'opacity-50 bg-light' : '' }
            .card-body.py-3
              = link_to users_team_task_path(task), class: 'text-decoration-none text-dark' do
                %h5.card-title.fw-semibold.mb-2= task.title
              %p.mb-2= h(task.description)
              = button_to task.completed? ? '完了を取り消す' : '完了にする',
                          toggle_users_team_task_path(task),
                          method: :patch,
                          class: "btn btn-sm #{task.completed? ? 'btn-danger' : 'btn-outline-success'}"
      - else
        %p タスクがありません。

app/views/users/teams/tasks/_form.html.haml
.row.justify-content-center
  .col-md-6
    = simple_form_for([:users, team, task]) do |f|
      .form-inputs
        = f.input :title, autofocus: true
        = f.input :description, as: :text, input_html: { rows: 5 }

      .form-actions.text-center
        = f.button :submit, class: 'btn btn-outline-primary'

app/views/users/teams/tasks/edit.html.haml
%h2.text-center.mb-3 タスク編集
= render 'users/teams/tasks/form', team: @team, task: @task

app/views/users/teams/tasks/new.html.haml
%h2.text-center.mb-3 タスク作成
= render 'users/teams/tasks/form', team: @team, task: @task

app/views/users/teams/tasks/show.html.haml
%h2.text-center.mb-3 タスク詳細

.row.justify-content-center
  .col-md-6.text-center
    .card.shadow-sm.mb-3
      .card-body.py-3
        .card-title.fw-bold= @task.title
        %p.mb-3= h(@task.description)
        = button_to @task.completed? ? '完了を取り消す' : '完了にする',
                    toggle_users_team_task_path(@task),
                    method: :patch,
                    class: "btn btn-sm #{@task.completed? ? 'btn-danger' : 'btn-outline-success'}"

    .mb-3.d-flex.justify-content-center.gap-3
      = link_to '一覧に戻る', users_team_path, class: 'btn btn-outline-secondary'
      = link_to '編集する', edit_users_team_task_path(@task), class: 'btn btn-outline-warning'
      = button_to '削除する',
                  users_team_task_path(@task),
                  method: :delete,
                  data: { turbo_confirm: '本当に削除しますか？' },
                  form: { class: 'd-inline' },
                  class: 'btn btn-outline-danger'